### ISSUE TITLE
cb

### ISSUE THREAD

**Issue by chrismurrph** [akmiller78/tut-omnext-tempids#1]
Not exactly an issue, but can I ask what `cb` normally stands for? Would make my reading of the code easier... Thanks

**Comment by akmiller78** [comment]
Sure, I'll change that. It's actually the callback function that gets run with the data returned by the remote.

**Comment by akmiller78** [comment]
Updated code with full name 'callback' and added couple comments in that area to clarify.

**Comment by chrismurrph** [comment]
Thanks. Again not an issue - I get that there's a UI tree, and normalized local table data (using Idents). So what's the AST? I know it stands for abstract syntax tree, but I don't yet get what this means in the context of Om/Next.

**Comment by akmiller78** [comment]
It's exactly that, the AST of the query expression that's provided. Om.next converts the expressions into an AST for processing. So a query expression of something like [(users/create { ... }] is converted into an AST. Put some printlns around that call to see the remote and see the result of running query->ast on it.
